name: Odt tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch from Github
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Run tests with Maven
        run: |
          cd odt_service
          mvn -B test --file pom.xml