name: Audio tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch from Github
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

        - name: Run tests with Mocha
          run: |
            cd translation
            npm test